name: Autoversion

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install Commitizen
      run: pip install commitizen
    - name: Bump version
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        cz bump --yes --changelog
        git push --follow-tags

